/**
 * Image generation stub.
 * Architecturally present from day one, but returns null during early development.
 * When wired in, this will call Replicate/OpenAI and return a URL.
 */
export async function generateChapterImage(
  _imagePrompt: string,
  _stylePrompt: string
): Promise<string | null> {
  // STUB: Image generation is deferred until the story engine and reading
  // experience are stable. The image_prompt field is always generated by
  // the story engine — actual image rendering is wired in later.
  return null
}
